# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageDisplayer = QtWidgets.QLabel(self.centralwidget)
        self.imageDisplayer.setGeometry(QtCore.QRect(60, 40, 1051, 561))
        self.imageDisplayer.setText("")
        self.imageDisplayer.setObjectName("imageDisplayer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menu = QtWidgets.QMenu(self.menuSetting)
        self.menu.setObjectName("menu")
        self.menuImage_Processing = QtWidgets.QMenu(self.menubar)
        self.menuImage_Processing.setObjectName("menuImage_Processing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionSave_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.action_ROI = QtWidgets.QAction(MainWindow)
        self.action_ROI.setObjectName("action_ROI")
        self.action_showHisto = QtWidgets.QAction(MainWindow)
        self.action_showHisto.setObjectName("action_showHisto")
        self.actionRestoreOriginal = QtWidgets.QAction(MainWindow)
        self.actionRestoreOriginal.setObjectName("actionRestoreOriginal")
        self.action_convertGrayScale = QtWidgets.QAction(MainWindow)
        self.action_convertGrayScale.setObjectName("action_convertGrayScale")
        self.action_thresholding = QtWidgets.QAction(MainWindow)
        self.action_thresholding.setObjectName("action_thresholding")
        self.action_histoEqualization = QtWidgets.QAction(MainWindow)
        self.action_histoEqualization.setObjectName("action_histoEqualization")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionSave_Image)
        self.menu.addAction(self.action_convertGrayScale)
        self.menuSetting.addAction(self.action_ROI)
        self.menuSetting.addAction(self.action_showHisto)
        self.menuSetting.addAction(self.menu.menuAction())
        self.menuSetting.addAction(self.actionRestoreOriginal)
        self.menuImage_Processing.addAction(self.action_thresholding)
        self.menuImage_Processing.addAction(self.action_histoEqualization)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuImage_Processing.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "影像處理開發平台"))
        self.menuFile.setTitle(_translate("MainWindow", "檔案"))
        self.menuSetting.setTitle(_translate("MainWindow", "設定"))
        self.menu.setTitle(_translate("MainWindow", "顯示或改變色彩空間"))
        self.menuImage_Processing.setTitle(_translate("MainWindow", "影像處理"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen_Image.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Image.setText(_translate("MainWindow", "Save Image"))
        self.actionSave_Image.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_ROI.setText(_translate("MainWindow", "設定ROI"))
        self.action_showHisto.setText(_translate("MainWindow", "顯示直方圖"))
        self.actionRestoreOriginal.setText(_translate("MainWindow", "恢復原始圖片"))
        self.action_convertGrayScale.setText(_translate("MainWindow", "轉換灰階"))
        self.action_thresholding.setText(_translate("MainWindow", "影像二值化"))
        self.action_histoEqualization.setText(_translate("MainWindow", "直方圖等化"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
