# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warpAffine.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):

    def __init__(self):
        super(Ui_Dialog, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 532)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 470, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.rotateFrame = QtWidgets.QFrame(Dialog)
        self.rotateFrame.setGeometry(QtCore.QRect(70, 30, 461, 80))
        self.rotateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rotateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rotateFrame.setObjectName("rotateFrame")
        self.rotateSlider = QtWidgets.QSlider(self.rotateFrame)
        self.rotateSlider.setGeometry(QtCore.QRect(230, 30, 201, 22))
        self.rotateSlider.setMaximum(360)
        self.rotateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rotateSlider.setObjectName("rotateSlider")
        self.rotateTextLabel = QtWidgets.QLabel(self.rotateFrame)
        self.rotateTextLabel.setGeometry(QtCore.QRect(20, 30, 58, 15))
        self.rotateTextLabel.setObjectName("rotateTextLabel")
        self.rotateValueLabel = QtWidgets.QLabel(self.rotateFrame)
        self.rotateValueLabel.setGeometry(QtCore.QRect(120, 30, 58, 15))
        self.rotateValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rotateValueLabel.setObjectName("rotateValueLabel")
        self.translateXFrame = QtWidgets.QFrame(Dialog)
        self.translateXFrame.setGeometry(QtCore.QRect(70, 140, 461, 80))
        self.translateXFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.translateXFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.translateXFrame.setObjectName("translateXFrame")
        self.translateXSlider = QtWidgets.QSlider(self.translateXFrame)
        self.translateXSlider.setGeometry(QtCore.QRect(230, 30, 201, 22))
        self.translateXSlider.setMinimum(-100)
        self.translateXSlider.setMaximum(100)
        self.translateXSlider.setOrientation(QtCore.Qt.Horizontal)
        self.translateXSlider.setObjectName("translateXSlider")
        self.translateTextLabel = QtWidgets.QLabel(self.translateXFrame)
        self.translateTextLabel.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.translateTextLabel.setObjectName("translateTextLabel")
        self.translateXValueLabel = QtWidgets.QLabel(self.translateXFrame)
        self.translateXValueLabel.setGeometry(QtCore.QRect(140, 30, 58, 15))
        self.translateXValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.translateXValueLabel.setObjectName("translateXValueLabel")
        self.translateYFrame = QtWidgets.QFrame(Dialog)
        self.translateYFrame.setGeometry(QtCore.QRect(70, 250, 461, 80))
        self.translateYFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.translateYFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.translateYFrame.setObjectName("translateYFrame")
        self.translateYSlider = QtWidgets.QSlider(self.translateYFrame)
        self.translateYSlider.setGeometry(QtCore.QRect(230, 30, 201, 22))
        self.translateYSlider.setMinimum(-100)
        self.translateYSlider.setMaximum(100)
        self.translateYSlider.setOrientation(QtCore.Qt.Horizontal)
        self.translateYSlider.setObjectName("translateYSlider")
        self.translateYTextLabel = QtWidgets.QLabel(self.translateYFrame)
        self.translateYTextLabel.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.translateYTextLabel.setObjectName("translateYTextLabel")
        self.translateYValueLabel = QtWidgets.QLabel(self.translateYFrame)
        self.translateYValueLabel.setGeometry(QtCore.QRect(140, 30, 58, 15))
        self.translateYValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.translateYValueLabel.setObjectName("translateYValueLabel")
        self.flipFrame = QtWidgets.QFrame(Dialog)
        self.flipFrame.setGeometry(QtCore.QRect(70, 360, 461, 80))
        self.flipFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.flipFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.flipFrame.setObjectName("flipFrame")
        self.flipTextLabel = QtWidgets.QLabel(self.flipFrame)
        self.flipTextLabel.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.flipTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flipTextLabel.setObjectName("flipTextLabel")
        self.flipCheckBox = QtWidgets.QCheckBox(self.flipFrame)
        self.flipCheckBox.setGeometry(QtCore.QRect(320, 30, 85, 19))
        self.flipCheckBox.setText("")
        self.flipCheckBox.setObjectName("flipCheckBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "仿射轉換"))
        self.rotateTextLabel.setText(_translate("Dialog", "旋轉角度"))
        self.rotateValueLabel.setText(_translate("Dialog", "0"))
        self.translateTextLabel.setText(_translate("Dialog", "水平平移(百分比)"))
        self.translateXValueLabel.setText(_translate("Dialog", "0"))
        self.translateYTextLabel.setText(_translate("Dialog", "垂直平移(百分比)"))
        self.translateYValueLabel.setText(_translate("Dialog", "0"))
        self.flipTextLabel.setText(_translate("Dialog", "是否翻轉"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
